### ISSUE TITLE
Improve centering (some slides feel off)

### ISSUE THREAD

**Issue by sjoerdly** [ScrumFacilitators/measuringoutcome-cht#4]
Hey! 

This is a minor issue. The centering of text feels off in some slides. This may have been to do with teh pdf preview option of Github (viewed in-frame the current pdf). Or the layout and rendering of chinese characters...

But it may be good, before releasing, to have a thorough look at the centering, and remove stray space characters that could influence centering and review the positioning of the containing text boxes.

**Comment by ctonylee** [comment]
Thank you @sjoerdly  for pointing out the "centering of text" problem.  
I think it is because the text-boxes are having different widths and are not aligned.  
I am working on updating all the KVM slides' text boxes to have the same with, I believe this will address the text centering concern. 

![](https://user-images.githubusercontent.com/1815759/103258045-98c3ee00-49ce-11eb-970b-f4c8968ad484.png)

**Comment by ctonylee** [comment]
closing issue because #5 has updated the alignment
